openapi: 3.0.1
info:
  title: Online Order API
  version: 1.0.0
  description: >
    A basic API for working with Swagger tools, providing endpoints for managing
    user groups and records, as well as user registration and LINE login.
paths:
  components:
    securitySchemes:
      BearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
  security:
    - BearerAuth: []
  /mrsaccountant/user/groups:
    get:
      summary: Retrieve all groups for the authenticated user
      description: Fetches all groups associated with the authenticated user.
      operationId: getUserGroups
      responses:
        '200':
          description: A list of user groups.
          content:
            application/json:
              examples:
                userAllGroups:
                  summary: Sample response
                  value: |
                    [
                        {
                            "groupName": "Marketing Team",
                            "createdAt": "2024-11-21",
                            "groupTransactions": [],
                            "groupId": 2
                        },
                        {
                            "groupName": "Test Group",
                            "createdAt": "2024-11-21",
                            "groupTransactions": [],
                            "groupId": 6
                        }
                    ]
        '204':
          description: No groups found for the user.
        default:
          description: An error occurred while retrieving user groups.
      tags:
        - User Groups
    post:
      summary: Create a new group for the authenticated user
      description: Adds a new group to the authenticated user's account.
      operationId: createUserGroup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                groupName:
                  type: string
                  description: The name of the new group.
              required:
                - groupName
      responses:
        '201':
          description: Group created successfully.
          content:
            application/json:
              schema:
                type: string
                example: Group added successfully!
        '400':
          description: Invalid group data provided.
        default:
          description: An error occurred while creating the group.
      tags:
        - User Groups
  /user/groups/{groupId}:
    delete:
      summary: Delete a group by its ID
      description: Deletes a user group specified by its unique ID.
      operationId: deleteUserGroup
      parameters:
        - name: groupId
          in: path
          required: true
          description: The unique identifier of the group to delete.
          schema:
            type: integer
      responses:
        '202':
          description: Group deleted successfully.
          content:
            application/json:
              schema:
                type: string
                example: Group deleted successfully!
        '404':
          description: Group not found.
        default:
          description: An error occurred while deleting the group.
      tags:
        - User Groups
  /mrsaccountant/user/records:
    get:
      summary: Get user records
      description: Fetch user records by date range or all records if no date range is provided.
      operationId: getUserRecords
      parameters:
        - name: startdate
          in: query
          required: false
          description: The start date for filtering records (format: yyyy-MM-dd).
          schema:
            type: string
            format: date
        - name: enddate
          in: query
          required: false
          description: The end date for filtering records (format: yyyy-MM-dd).
          schema:
            type: string
            format: date
      responses:
        '200':
          description: A list of user records.
          content:
            application/json:
              examples:
                userRecords:
                  summary: Sample response
                  value: |
                    [
                        {
                            "name": "Groceries",
                            "amount": 150.5,
                            "type": "EXPENSE",
                            "date": "2024-11-22",
                            "category": "test5",
                            "recordId": 1
                        }
                    ]
        default:
          description: An error occurred while retrieving records.
      tags:
        - Records
    post:
      summary: Add a new record
      description: Add a new record for the authenticated user.
      operationId: addUserRecord
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the record (e.g., item or expense/income name).
                amount:
                  type: number
                  format: double
                  description: The monetary amount of the record.
                type:
                  type: string
                  description: The type of the record, either `INCOME` or `EXPENSE`.
                  enum:
                    - INCOME
                    - EXPENSE
                date:
                  type: string
                  format: date
                  description: The date associated with the record (e.g., transaction date).
                category:
                  type: string
                  description: The category of the record (e.g., Food, Travel, Salary).
              required:
                - name
                - amount
                - type
                - date
                - category
      responses:
        '201':
          description: Record added successfully.
          content:
            application/json:
              schema:
                type: string
                example: Record added successfully!
        '400':
          description: Invalid record data provided.
        default:
          description: An error occurred while adding the record.
      tags:
        - Records
  /mrsaccountant/user/records/{id}:
    delete:
      summary: Delete a record by its unique identifier
      description: Deletes a record by its unique identifier.
      operationId: deleteUserRecord
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the record to delete.
          schema:
            type: integer
      responses:
        '202':
          description: Record deleted successfully.
          content:
            application/json:
              schema:
                type: string
                example: Record deleted successfully!
        '404':
          description: Record not found.
        default:
          description: An error occurred while deleting the record.
      tags:
        - Records
  /auth/line:
    post:
      summary: LINE login for user authentication
      description: Allows a user to log in using their LINE account and receive a JWT token.
      operationId: lineLogin
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                idToken:
                  type: string
                  description: The LINE ID token for authentication.
              required:
                - idToken
      responses:
        '200':
          description: User authenticated successfully.
          content:
            application/json:
              examples:
                lineLoginSuccess:
                  summary: Sample response
                  value: |
                    {
                        "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                        "userId": "JohnDoe"
                    }
        '400':
          description: Invalid LINE ID token provided.
        '500':
          description: An unexpected error occurred.
      tags:
        - Authentication
